### ISSUE TITLE
TypeScript code blocks aren't syntax highlighted

### ISSUE THREAD

**Issue by tusharsadhwani** [fossunited/monschool-website#41]
````
```typescript
let x = 5
```
````

The output here doesn't get syntax highlighted. Same with `{.typescript .example}`

**Comment by anandology** [comment]
Please try with 

    ```{.javascript .example}
    ```
    
I guess the javascript mode of codemirror supports both javascript and typescript.

**Comment by anandology** [comment]
This issue is fixed now.
